version: "3.7"
services:
    fmanager:
        build:
            args:
                user: filip
                uid: 1000
            context: ./
            dockerfile: ./docker/php/Dockerfile
        container_name: fmanager-container
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
        networks:
            - fmananager

    node:
        image: node:18-buster
        container_name: fmanager-node
        tty: true
        user: "1000:1000"
        volumes:
            - .:/var/www
        working_dir: /var/www
        command: bash -c "npm install"
    nginx:
        image: nginx:alpine
        container_name: fmanager-nginx
        restart: unless-stopped
        ports:
            - 8001:80
        volumes:
            - ./:/var/www
            - ./docker/nginx:/etc/nginx/conf.d/
        networks:
            - fmananager
networks:
    fmananager:
        driver: bridge

