version: "3.7"
services:
    fmanager:
        build:
            args:
                user: filip
                uid: 1000
            context: ./
            dockerfile: ./docker/php/Dockerfile
        container_name: fmanager-container
        restart: unless-stopped
        working_dir: /var/www
        environment:
            - DB_HOST=host.docker.internal
        extra_hosts:
            - "host.docker.internal:host-gateway"
        volumes:
            - ./:/var/www
        networks:
            - fmananager
    nginx:
        image: nginx:alpine
        container_name: fmanager-nginx
        restart: unless-stopped
        ports:
            - 8001:80
        volumes:
            - ./:/var/www
            - ./docker/nginx:/etc/nginx/conf.d/
        networks:
            - fmananager
networks:
    fmananager:
        driver: bridge

