INSERT INTO `base_cities` (`name`, `population`, `country_code`) VALUES ('London', 7285000, 'GBR');
INSERT INTO `base_cities` (`name`, `population`, `country_code`) VALUES ('Birmingham', 1013000, 'GBR');
INSERT INTO `base_cities` (`name`, `population`, `country_code`) VALUES ('Glasgow', 619680, 'GBR');
INSERT INTO `base_cities` (`name`, `population`, `country_code`) VALUES ('Liverpool', 461000, 'GBR');
INSERT INTO `base_cities` (`name`, `population`, `country_code`) VALUES ('Edinburgh', 450180, 'GBR');
INSERT INTO `base_cities` (`name`, `population`, `country_code`) VALUES ('Sheffield', 431607, 'GBR');
INSERT INTO `base_cities` (`name`, `population`, `country_code`) VALUES ('Manchester', 430000, 'GBR');
INSERT INTO `base_cities` (`name`, `population`, `country_code`) VALUES ('Leeds', 424194, 'GBR');
INSERT INTO `base_cities` (`name`, `population`, `country_code`) VALUES ('Bristol', 402000, 'GBR');
INSERT INTO `base_cities` (`name`, `population`, `country_code`) VALUES ('Cardiff', 321000, 'GBR');
INSERT INTO `base_cities` (`name`, `population`, `country_code`) VALUES ('Coventry', 304000, 'GBR');
INSERT INTO `base_cities` (`name`, `population`, `country_code`) VALUES ('Leicester', 294000, 'GBR');
INSERT INTO `base_cities` (`name`, `population`, `country_code`) VALUES ('Bradford', 289376, 'GBR');
INSERT INTO `base_cities` (`name`, `population`, `country_code`) VALUES ('Belfast', 287500, 'GBR');
INSERT INTO `base_cities` (`name`, `population`, `country_code`) VALUES ('Nottingham', 287000, 'GBR');
INSERT INTO `base_cities` (`name`, `population`, `country_code`) VALUES ('Kingston upon Hull', 262000, 'GBR');
INSERT INTO `base_cities` (`name`, `population`, `country_code`) VALUES ('Plymouth', 253000, 'GBR');
INSERT INTO `base_cities` (`name`, `population`, `country_code`) VALUES ('Stoke-on-Trent', 252000, 'GBR');
INSERT INTO `base_cities` (`name`, `population`, `country_code`) VALUES ('Wolverhampton', 242000, 'GBR');
INSERT INTO `base_cities` (`name`, `population`, `country_code`) VALUES ('Derby', 236000, 'GBR');
INSERT INTO `base_cities` (`name`, `population`, `country_code`) VALUES ('Swansea', 230000, 'GBR');
INSERT INTO `base_cities` (`name`, `population`, `country_code`) VALUES ('Southampton', 216000, 'GBR');
INSERT INTO `base_cities` (`name`, `population`, `country_code`) VALUES ('Aberdeen', 213070, 'GBR');
INSERT INTO `base_cities` (`name`, `population`, `country_code`) VALUES ('Northampton', 196000, 'GBR');
INSERT INTO `base_cities` (`name`, `population`, `country_code`) VALUES ('Dudley', 192171, 'GBR');
INSERT INTO `base_cities` (`name`, `population`, `country_code`) VALUES ('Portsmouth', 190000, 'GBR');
INSERT INTO `base_cities` (`name`, `population`, `country_code`) VALUES ('Newcastle upon Tyne', 189150, 'GBR');
INSERT INTO `base_cities` (`name`, `population`, `country_code`) VALUES ('Sunderland', 183310, 'GBR');
INSERT INTO `base_cities` (`name`, `population`, `country_code`) VALUES ('Luton', 183000, 'GBR');
INSERT INTO `base_cities` (`name`, `population`, `country_code`) VALUES ('Swindon', 180000, 'GBR');
INSERT INTO `base_cities` (`name`, `population`, `country_code`) VALUES ('Southend-on-Sea', 176000, 'GBR');
INSERT INTO `base_cities` (`name`, `population`, `country_code`) VALUES ('Walsall', 174739, 'GBR');
INSERT INTO `base_cities` (`name`, `population`, `country_code`) VALUES ('Bournemouth', 162000, 'GBR');
INSERT INTO `base_cities` (`name`, `population`, `country_code`) VALUES ('Peterborough', 156000, 'GBR');
INSERT INTO `base_cities` (`name`, `population`, `country_code`) VALUES ('Brighton', 156124, 'GBR');
INSERT INTO `base_cities` (`name`, `population`, `country_code`) VALUES ('Blackpool', 151000, 'GBR');
INSERT INTO `base_cities` (`name`, `population`, `country_code`) VALUES ('Dundee', 146690, 'GBR');
INSERT INTO `base_cities` (`name`, `population`, `country_code`) VALUES ('West Bromwich', 146386, 'GBR');
INSERT INTO `base_cities` (`name`, `population`, `country_code`) VALUES ('Reading', 148000, 'GBR');
INSERT INTO `base_cities` (`name`, `population`, `country_code`) VALUES ('Oldbury/Smethwick (Warley)', 145542, 'GBR');
INSERT INTO `base_cities` (`name`, `population`, `country_code`) VALUES ('Middlesbrough', 145000, 'GBR');
INSERT INTO `base_cities` (`name`, `population`, `country_code`) VALUES ('Huddersfield', 143726, 'GBR');
INSERT INTO `base_cities` (`name`, `population`, `country_code`) VALUES ('Oxford', 144000, 'GBR');
INSERT INTO `base_cities` (`name`, `population`, `country_code`) VALUES ('Poole', 141000, 'GBR');
INSERT INTO `base_cities` (`name`, `population`, `country_code`) VALUES ('Bolton', 139020, 'GBR');
INSERT INTO `base_cities` (`name`, `population`, `country_code`) VALUES ('Blackburn', 140000, 'GBR');
INSERT INTO `base_cities` (`name`, `population`, `country_code`) VALUES ('Newport', 139000, 'GBR');
INSERT INTO `base_cities` (`name`, `population`, `country_code`) VALUES ('Preston', 135000, 'GBR');
INSERT INTO `base_cities` (`name`, `population`, `country_code`) VALUES ('Stockport', 132813, 'GBR');
INSERT INTO `base_cities` (`name`, `population`, `country_code`) VALUES ('Norwich', 124000, 'GBR');
INSERT INTO `base_cities` (`name`, `population`, `country_code`) VALUES ('Rotherham', 121380, 'GBR');
INSERT INTO `base_cities` (`name`, `population`, `country_code`) VALUES ('Cambridge', 121000, 'GBR');
INSERT INTO `base_cities` (`name`, `population`, `country_code`) VALUES ('Watford', 113080, 'GBR');
INSERT INTO `base_cities` (`name`, `population`, `country_code`) VALUES ('Ipswich', 114000, 'GBR');
INSERT INTO `base_cities` (`name`, `population`, `country_code`) VALUES ('Slough', 112000, 'GBR');
INSERT INTO `base_cities` (`name`, `population`, `country_code`) VALUES ('Exeter', 111000, 'GBR');
INSERT INTO `base_cities` (`name`, `population`, `country_code`) VALUES ('Cheltenham', 106000, 'GBR');
INSERT INTO `base_cities` (`name`, `population`, `country_code`) VALUES ('Gloucester', 107000, 'GBR');
INSERT INTO `base_cities` (`name`, `population`, `country_code`) VALUES ('Saint Helens', 106293, 'GBR');
INSERT INTO `base_cities` (`name`, `population`, `country_code`) VALUES ('Sutton Coldfield', 106001, 'GBR');
INSERT INTO `base_cities` (`name`, `population`, `country_code`) VALUES ('York', 104425, 'GBR');
INSERT INTO `base_cities` (`name`, `population`, `country_code`) VALUES ('Oldham', 103931, 'GBR');
INSERT INTO `base_cities` (`name`, `population`, `country_code`) VALUES ('Basildon', 100924, 'GBR');
INSERT INTO `base_cities` (`name`, `population`, `country_code`) VALUES ('Wigan', 103608, 'GBR');
INSERT INTO `base_cities` (`name`, `population`, `country_code`) VALUES ('Bury', 78723, 'GBR');
INSERT INTO `base_cities` (`name`, `population`, `country_code`) VALUES ('Barnsley', 91297, 'GBR');
INSERT INTO `base_cities` (`name`, `population`, `country_code`) VALUES ('Burnley', 73021, 'GBR');
