INSERT INTO `base_clubs` (`id`, `name`, `country_code`, `city_id`, `stadium_id`, `rank`, `rank_academy`, `rank_training`, `competition_id`) VALUES (1, 'Arsenal', 'GBR', 1, 11, 17, 18, 17, 1);
INSERT INTO `base_clubs` (`id`, `name`, `country_code`, `city_id`, `stadium_id`, `rank`, `rank_academy`, `rank_training`, `competition_id`) VALUES (2, 'Liverpool', 'GBR', 4, 2, 18, 14, 17, 1);
INSERT INTO `base_clubs` (`id`, `name`, `country_code`, `city_id`, `stadium_id`, `rank`, `rank_academy`, `rank_training`, `competition_id`) VALUES (3, 'Manchester City', 'GBR', 7, 12, 18, 17, 18, 1);
INSERT INTO `base_clubs` (`id`, `name`, `country_code`, `city_id`, `stadium_id`, `rank`, `rank_academy`, `rank_training`, `competition_id`) VALUES (4, 'Leicester City', 'GBR', 12, 20, 14, 13, 14, 1);
INSERT INTO `base_clubs` (`id`, `name`, `country_code`, `city_id`, `stadium_id`, `rank`, `rank_academy`, `rank_training`, `competition_id`) VALUES (5, 'Chelsea', 'GBR', 1, 37, 17, 18, 16, 1);
INSERT INTO `base_clubs` (`id`, `name`, `country_code`, `city_id`, `stadium_id`, `rank`, `rank_academy`, `rank_training`, `competition_id`) VALUES (6, 'Tottenham Hotspur', 'GBR', 1, 47, 16, 15, 16, 1);
INSERT INTO `base_clubs` (`id`, `name`, `country_code`, `city_id`, `stadium_id`, `rank`, `rank_academy`, `rank_training`, `competition_id`) VALUES (7, 'Sheffield United', 'GBR', 6, 4, 12, 11, 13, 1);
INSERT INTO `base_clubs` (`id`, `name`, `country_code`, `city_id`, `stadium_id`, `rank`, `rank_academy`, `rank_training`, `competition_id`) VALUES (8, 'Manchester United', 'GBR', 7, 26, 19, 16, 18, 1);
INSERT INTO `base_clubs` (`id`, `name`, `country_code`, `city_id`, `stadium_id`, `rank`, `rank_academy`, `rank_training`, `competition_id`) VALUES (9, 'Wolverhampton Wanderers', 'GBR', 19, 24, 14, 14, 14, 1);
INSERT INTO `base_clubs` (`id`, `name`, `country_code`, `city_id`, `stadium_id`, `rank`, `rank_academy`, `rank_training`, `competition_id`) VALUES (10, 'Everton', 'GBR', 4, 16, 15, 13, 14, 1);
INSERT INTO `base_clubs` (`id`, `name`, `country_code`, `city_id`, `stadium_id`, `rank`, `rank_academy`, `rank_training`, `competition_id`) VALUES (11, 'Burnley', 'GBR', 68, 41, 11, 10, 13, 1);
INSERT INTO `base_clubs` (`id`, `name`, `country_code`, `city_id`, `stadium_id`, `rank`, `rank_academy`, `rank_training`, `competition_id`) VALUES (12, 'Newcastle United', 'GBR', 27, 34, 14, 11, 13, 1);
INSERT INTO `base_clubs` (`id`, `name`, `country_code`, `city_id`, `stadium_id`, `rank`, `rank_academy`, `rank_training`, `competition_id`) VALUES (13, 'Southampton', 'GBR', 22, 35, 13, 17, 15, 1);
INSERT INTO `base_clubs` (`id`, `name`, `country_code`, `city_id`, `stadium_id`, `rank`, `rank_academy`, `rank_training`, `competition_id`) VALUES (14, 'Crystal Palace', 'GBR', 1, 32, 12, 10, 13, 1);
INSERT INTO `base_clubs` (`id`, `name`, `country_code`, `city_id`, `stadium_id`, `rank`, `rank_academy`, `rank_training`, `competition_id`) VALUES (15, 'Brighton and Have Albion', 'GBR', 35, 1, 10, 10, 13, 1);
INSERT INTO `base_clubs` (`id`, `name`, `country_code`, `city_id`, `stadium_id`, `rank`, `rank_academy`, `rank_training`, `competition_id`) VALUES (16, 'AFC Bournemouth', 'GBR', 1, 48, 11, 11, 12, 1);
INSERT INTO `base_clubs` (`id`, `name`, `country_code`, `city_id`, `stadium_id`, `rank`, `rank_academy`, `rank_training`, `competition_id`) VALUES (17, 'Aston Villa', 'GBR', 2, 45, 13, 12, 14, 1);
INSERT INTO `base_clubs` (`id`, `name`, `country_code`, `city_id`, `stadium_id`, `rank`, `rank_academy`, `rank_training`, `competition_id`) VALUES (18, 'West Ham United', 'GBR', 1, 27, 14, 13, 14, 1);
INSERT INTO `base_clubs` (`id`, `name`, `country_code`, `city_id`, `stadium_id`, `rank`, `rank_academy`, `rank_training`, `competition_id`) VALUES (19, 'Watford', 'GBR', 53, 44, 12, 11, 12, 1);
INSERT INTO `base_clubs` (`id`, `name`, `country_code`, `city_id`, `stadium_id`, `rank`, `rank_academy`, `rank_training`, `competition_id`) VALUES (20, 'Norwich City', 'GBR', 50, 7, 10, 11, 11, 1);
