INSERT INTO `positions` (`id`, `name`, `alias`) VALUES (1, 'Center back', 'CB'),
(2, 'Left back', 'LB'),
(3, 'Left wingback', 'LWB'),
(4, 'Right back', 'RB'),
(5, 'Right wingback', 'RWB'),
(6, 'Defensive midfield center', 'DMC'),
(7, 'Center midfielder', 'CM'),
(8, 'Left wing', 'LW'),
(9, 'Left forward', 'LF'),
(10, 'Attacking midfield center', 'AMC'),
(11, 'Right wing', 'RW'),
(12, 'Right forward', 'RF'),
(13, 'Center forward', 'CF'),
(14, 'Striker', 'ST');
