<?php

namespace AppBundle\GameEngine\GameData\InitialSeed\DataByCountry;

class DataSpain
{
    public static function clubs
    {
        return [
            [
                'name' => 'Alavés',
                'league_id' => 2,
                'city' => 14,
                'country' => 2,
                'coefficient' => 0,
                'coeff1' => 0,
                'coeff2' => 0,
                'coeff3' => 0,
                'coeff4' => 0,
                'coeff5' => 0,
                'world_ranking' => 2800,
                'stadium_id' => 21,
                'account_balance' => 3,
            ],
            [
                'name' => 'Athletic Bilbao',
                'league_id' => 2,
                'city' => 15,
                'country' => 2,
                'coefficient' => 119,
                'coeff1' => 22,
                'coeff2' => 28,
                'coeff3' => 29,
                'coeff4' => 28,
                'coeff5' => 12,
                'world_ranking' => 8300,
                'stadium_id' => 22,
                'account_balance' => 7,
            ],
            [
                'name' => 'Atlético Madrid',
                'league_id' => 2,
                'city' => 16,
                'country' => 2,
                'coefficient' => 140,
                'coeff1' => 33,
                'coeff2' => 22,
                'coeff3' => 28,
                'coeff4' => 29,
                'coeff5' => 28,
                'world_ranking' => 8200,
                'stadium_id' => 23,
                'account_balance' => 70,
            ],
            [
                'name' => 'Barcelona',
                'league_id' => 2,
                'city' => 17,
                'country' => 2,
                'coefficient' => 132,
                'coeff1' => 24,
                'coeff2' => 34,
                'coeff3' => 26,
                'coeff4' => 23,
                'coeff5' => 25,
                'world_ranking' => 9500,
                'stadium_id' => 24,
                'account_balance' => 60,
            ],
            [
                'name' => 'Celta Vigo',
                'league_id' => 2,
                'city' => 18,
                'country' => 2,
                'coefficient' => 19,
                'coeff1' => 0,
                'coeff2' => 0,
                'coeff3' => 19,
                'coeff4' => 0,
                'coeff5' => 0,
                'world_ranking' => 4000,
                'stadium_id' => 25,
                'account_balance' => 20,
            ],
            [
                'name' => 'Eibar',
                'league_id' => 2,
                'city' => 19,
                'country' => 2,
                'coefficient' => 0,
                'coeff1' => 0,
                'coeff2' => 0,
                'coeff3' => 0,
                'coeff4' => 0,
                'coeff5' => 0,
                'world_ranking' => 2700,
                'stadium_id' => 26,
                'account_balance' => 4,
            ],
            [
                'name' => 'Espanyol',
                'league_id' => 2,
                'city' => 17,
                'country' => 2,
                'coefficient' => 0,
                'coeff1' => 0,
                'coeff2' => 0,
                'coeff3' => 0,
                'coeff4' => 0,
                'coeff5' => 0,
                'world_ranking' => 3400,
                'stadium_id' => 27,
                'account_balance' => 11,
            ],
            [
                'name' => 'Getafe',
                'league_id' => 2,
                'city' => 20,
                'country' => 2,
                'coefficient' => 0,
                'coeff1' => 0,
                'coeff2' => 0,
                'coeff3' => 0,
                'coeff4' => 0,
                'coeff5' => 0,
                'world_ranking' => 3100,
                'stadium_id' => 28,
                'account_balance' => 8,
            ],
            [
                'name' => 'Girona',
                'league_id' => 2,
                'city' => 21,
                'country' => 2,
                'coefficient' => 0,
                'coeff1' => 0,
                'coeff2' => 0,
                'coeff3' => 0,
                'coeff4' => 0,
                'coeff5' => 0,
                'world_ranking' => 2700,
                'stadium_id' => 29,
                'account_balance' => 5,
            ],
            [
                'name' => 'Huesca',
                'league_id' => 2,
                'city' => 22,
                'country' => 2,
                'coefficient' => 0,
                'coeff1' => 0,
                'coeff2' => 0,
                'coeff3' => 0,
                'coeff4' => 0,
                'coeff5' => 0,
                'world_ranking' => 2500,
                'stadium_id' => 30,
                'account_balance' => 3,
            ],
            [
                'name' => 'Leganés',
                'league_id' => 2,
                'city' => 23,
                'country' => 2,
                'coefficient' => 0,
                'coeff1' => 0,
                'coeff2' => 0,
                'coeff3' => 0,
                'coeff4' => 0,
                'coeff5' => 0,
                'world_ranking' => 2500,
                'stadium_id' => 31,
                'account_balance' => 3,
            ],
            [
                'name' => 'Levante',
                'league_id' => 2,
                'city' => 24,
                'country' => 2,
                'coefficient' => 0,
                'coeff1' => 0,
                'coeff2' => 0,
                'coeff3' => 0,
                'coeff4' => 0,
                'coeff5' => 0,
                'world_ranking' => 3100,
                'stadium_id' => 32,
                'account_balance' => 12,
            ],
            [
                'name' => 'Rayo Vallecano',
                'league_id' => 2,
                'city' => 16,
                'country' => 2,
                'coefficient' => 0,
                'coeff1' => 0,
                'coeff2' => 0,
                'coeff3' => 0,
                'coeff4' => 0,
                'coeff5' => 0,
                'world_ranking' => 3300,
                'stadium_id' => 33,
                'account_balance' => 14,
            ],
            [
                'name' => 'Real Betis',
                'league_id' => 2,
                'city' => 25,
                'country' => 2,
                'coefficient' => 6,
                'coeff1' => 0,
                'coeff2' => 0,
                'coeff3' => 0,
                'coeff4' => 0,
                'coeff5' => 6,
                'world_ranking' => 5000,
                'stadium_id' => 34,
                'account_balance' => 22,
            ],
            [
                'name' => 'Real Madrid',
                'league_id' => 2,
                'city' => 16,
                'country' => 2,
                'coefficient' => 162,
                'coeff1' => 35,
                'coeff2' => 29,
                'coeff3' => 33,
                'coeff4' => 33,
                'coeff5' => 32,
                'world_ranking' => 9600,
                'stadium_id' => 34,
                'account_balance' => 35,
            ],
        ];

        [
            'Alavés', 'Athletic Bilbao', 'Atlético Madrid', 'Barcelona', 'Celta Vigo', 'Eibar', 'Espanyol', 'Getafe', 'Girona', 'Huesca', 'Leganés', 'Levante', 'Rayo Vallecano', 'Real Betis', 'Real Madrid', 'Real Sociedad', 'Sevilla', 'Valencia', 'Valladolid', 'Villarreal'
        ];
    }
}