<?php

namespace AppBundle\GameEngine\GameData\ClubsByCountry;

class ClubsGermany
{
    public static function clubs()
    {
        return [
            [
                'name' => 'PSG',
                'coefficient' => 162, // uefa competitions coefficient
                'coeff1' => 35, // uefa coefficient for the last year to last five years
                'coeff2' => 29,
                'coeff3' => 33,
                'coeff4' => 33,
                'coeff5' => 32,
            ],
            [
                'name' => 'Lyon',
                'coefficient' => 60,
                'coeff1' => 15,
                'coeff2' => 2,
                'coeff3' => 7,
                'coeff4' => 22,
                'coeff5' => 14,
            ],
            [
                'name' => 'LOSC',
                'coefficient' => 5,
                'coeff1' => 0,
                'coeff2' => 4,
                'coeff3' => 0,
                'coeff4' => 1,
                'coeff5' => 0,
            ],
            [
                'name' => 'St-Etienne',
                'coefficient' => 25,
                'coeff1' => 2,
                'coeff2' => 5,
                'coeff3' => 9,
                'coeff4' => 9,
                'coeff5' => 0,
            ],
            [
                'name' => 'Marseille',
                'coefficient' => 32,
                'coeff1' => 4,
                'coeff2' => 0,
                'coeff3' => 9,
                'coeff4' => 0,
                'coeff5' => 19,
            ],
            [
                'name' => 'Montpellier',
                'coefficient' => 0,
                'coeff1' => 0,
                'coeff2' => 0,
                'coeff3' => 0,
                'coeff4' => 0,
                'coeff5' => 0,
            ],
            [
                'name' => 'Stade Reims',
                'coefficient' => 0,
                'coeff1' => 0,
                'coeff2' => 0,
                'coeff3' => 0,
                'coeff4' => 0,
                'coeff5' => 0,
            ],
            [
                'name' => 'OGC Nice',
                'coefficient' => 12,
                'coeff1' => 2,
                'coeff2' => 0,
                'coeff3' => 0,
                'coeff4' => 4,
                'coeff5' => 6,
            ],
            [
                'name' => 'Strasbourg',
                'coefficient' => 0,
                'coeff1' => 0,
                'coeff2' => 0,
                'coeff3' => 0,
                'coeff4' => 0,
                'coeff5' => 0,
            ],
            [
                'name' => 'Rennes',
                'coefficient' => 0,
                'coeff1' => 0,
                'coeff2' => 0,
                'coeff3' => 0,
                'coeff4' => 0,
                'coeff5' => 0,
            ],
            [
                'name' => 'Nimmes',
                'coefficient' => 0,
                'coeff1' => 0,
                'coeff2' => 0,
                'coeff3' => 0,
                'coeff4' => 0,
                'coeff5' => 0,
            ],
            [
                'name' => 'Angers',
                'coefficient' => 0,
                'coeff1' => 0,
                'coeff2' => 0,
                'coeff3' => 0,
                'coeff4' => 0,
                'coeff5' => 0,
            ],
            [
                'name' => 'Bordeaux',
                'coefficient' => 7,
                'coeff1' => 2,
                'coeff2' => 0,
                'coeff3' => 4,
                'coeff4' => 0,
                'coeff5' => 1,
            ],
            [
                'name' => 'Toulouse',
                'coefficient' => 0,
                'coeff1' => 0,
                'coeff2' => 0,
                'coeff3' => 0,
                'coeff4' => 0,
                'coeff5' => 0,
            ],
            [
                'name' => 'Nantes',
                'coefficient' => 0,
                'coeff1' => 0,
                'coeff2' => 0,
                'coeff3' => 0,
                'coeff4' => 0,
                'coeff5' => 0,
            ],
            [
                'name' => 'Monaco',
                'coefficient' => 57,
                'coeff1' => 0,
                'coeff2' => 21,
                'coeff3' => 5,
                'coeff4' => 25,
                'coeff5' => 6,
            ],
            [
                'name' => 'Amiens SC',
                'coefficient' => 0,
                'coeff1' => 0,
                'coeff2' => 0,
                'coeff3' => 0,
                'coeff4' => 0,
                'coeff5' => 0,
            ],
            [
                'name' => 'Dijon FCO',
                'coefficient' => 0,
                'coeff1' => 0,
                'coeff2' => 0,
                'coeff3' => 0,
                'coeff4' => 0,
                'coeff5' => 0,
            ],
            [
                'name' => 'Guingamp',
                'coefficient' => 0,
                'coeff1' => 0,
                'coeff2' => 0,
                'coeff3' => 0,
                'coeff4' => 0,
                'coeff5' => 0,
            ],
            [
                'name' => 'Caen',
                'coefficient' => 0,
                'coeff1' => 0,
                'coeff2' => 0,
                'coeff3' => 0,
                'coeff4' => 0,
                'coeff5' => 0,
            ],
        ];
    }
}