<?php

namespace AppBundle\GameEngine\GameData\ClubsByCountry;

class ClubsEngland
{
    public static function clubs
    {
        return [
            [
                'name' => 'Arsenal',
                'league_id' => 1,
                'city' => 1,
                'country' => 1,
                'coefficient' => 93, // uefa competitions coefficient
                'coeff1' => 19, // uefa coefficient for the last year to last five years
                'coeff2' => 15,
                'coeff3' => 26,
                'coeff4' => 18,
                'coeff5' => 18,
                'world_ranking' => 8600, // decides popularity of the club, range from 1-10 000, it gives more commercial inc, players wants to come and play here
                'stadium_id' => 1,
                'account_balance' => 180 //in milions of euros
            ],
            [
                'name' => 'Bournemouth',
                'league_id' => 1,
                'city' => 2,
                'country' => 1,
                'coefficient' => 0,
                'coeff1' => 0,
                'coeff2' => 0,
                'coeff3' => 0,
                'coeff4' => 0,
                'coeff5' => 0,
                'world_ranking' => 4000,
                'stadium_id' => 2,
                'account_balance' => 23,
            ],
            [
                'name' => 'Brighton & Hove Albion',
                'league_id' => 1,
                'city' => 3,
                'country' => 1,
                'coefficient' => 0,
                'coeff1' => 0,
                'coeff2' => 0,
                'coeff3' => 0,
                'coeff4' => 0,
                'coeff5' => 0,
                'world_ranking' => 3200,
                'stadium_id' => 3,
                'account_balance' => 4,
            ],
            [
                'name' => 'Burnley',
                'league_id' => 1,
                'city' => 4,
                'country' => 1,
                'coefficient' => 0,
                'coeff1' => 0,
                'coeff2' => 0,
                'coeff3' => 0,
                'coeff4' => 0,
                'coeff5' => 0,
                'world_ranking' => 3500,
                'stadium_id' => 4,
                'account_balance' => 8,
            ],
            [
                'name' => 'Cardiff City',
                'league_id' => 1,
                'city' => 5,
                'country' => 1,
                'coefficient' => 0,
                'coeff1' => 0,
                'coeff2' => 0,
                'coeff3' => 0,
                'coeff4' => 0,
                'coeff5' => 0,
                'world_ranking' => 4400,
                'stadium_id' => 5,
                'account_balance' => 9,
            ],
            [
                'name' => 'Chelsea',
                'league_id' => 1,
                'city' => 1,
                'country' => 1,
                'coefficient' => 82,
                'coeff1' => 25,
                'coeff2' => 21,
                'coeff3' => 18,
                'coeff4' => 0,
                'coeff5' => 18,
                'world_ranking' => 8500,
                'stadium_id' => 6,
                'account_balance' => 90,
            ],
            [
                'name' => 'Crystal Palace',
                'league_id' => 1,
                'city' => 1,
                'country' => 1,
                'coefficient' => 0,
                'coeff1' => 0,
                'coeff2' => 0,
                'coeff3' => 0,
                'coeff4' => 0,
                'coeff5' => 0,
                'world_ranking' => 4700,
                'stadium_id' => 7,
                'account_balance' => 18,
            ],
            [
                'name' => 'Everton',
                'league_id' => 1,
                'city' => 6,
                'country' => 1,
                'coefficient' => 17,
                'coeff1' => 0,
                'coeff2' => 14,
                'coeff3' => 0,
                'coeff4' => 0,
                'coeff5' => 3,
                'world_ranking' => 6000,
                'stadium_id' => 8,
                'account_balance' => 45,
            ],
            [
                'name' => 'Fulham',
                'league_id' => 1,
                'city' => 1,
                'country' => 1,
                'coefficient' => 0,
                'coeff1' => 0,
                'coeff2' => 0,
                'coeff3' => 0,
                'coeff4' => 0,
                'coeff5' => 0,
                'world_ranking' => 5200,
                'stadium_id' => 9,
                'account_balance' => 22,
            ],
            [
                'name' => 'Huddersfield Town',
                'league_id' => 1,
                'city' => 7,
                'country' => 1,
                'coefficient' => 0,
                'coeff1' => 0,
                'coeff2' => 0,
                'coeff3' => 0,
                'coeff4' => 0,
                'coeff5' => 0,
                'world_ranking' => 4100,
                'stadium_id' => 10,
                'account_balance' => 18,
            ],
            [
                'name' => 'Leicester City',
                'league_id' => 1,
                'city' => 8,
                'country' => 1,
                'coefficient' => 22,
                'coeff1' => 0,
                'coeff2' => 0,
                'coeff3' => 0,
                'coeff4' => 22,
                'coeff5' => 0,
                'world_ranking' => 5800,
                'stadium_id' => 11,
                'account_balance' => 45,
            ],
            [
                'name' => 'Liverpool',
                'league_id' => 1,
                'city' => 6,
                'country' => 1,
                'coefficient' => 62,
                'coeff1' => 0,
                'coeff2' => 10,
                'coeff3' => 22,
                'coeff4' => 0,
                'coeff5' => 30,
                'world_ranking' => 8700,
                'stadium_id' => 12,
                'account_balance' => 70,
            ],
            [
                'name' => 'Manchester City',
                'league_id' => 1,
                'city' => 9,
                'country' => 1,
                'coefficient' => 100,
                'coeff1' => 18,
                'coeff2' => 20,
                'coeff3' => 15,
                'coeff4' => 19,
                'coeff5' => 21,
                'world_ranking' => 8400,
                'stadium_id' => 13,
                'account_balance' => 110,
            ],
            [
                'name' => 'Manchester United',
                'league_id' => 1,
                'city' => 9,
                'country' => 1,
                'coefficient' => 82,
                'coeff1' => 23,
                'coeff2' => 0,
                'coeff3' => 13,
                'coeff4' => 26,
                'coeff5' => 20,
                'world_ranking' => 9500,
                'stadium_id' => 14,
                'account_balance' => 140,
            ],
            [
                'name' => 'Newcastle United',
                'league_id' => 1,
                'city' => 10,
                'country' => 1,
                'coefficient' => 0,
                'coeff1' => 0,
                'coeff2' => 0,
                'coeff3' => 0,
                'coeff4' => 0,
                'coeff5' => 0,
                'world_ranking' => 5400,
                'stadium_id' => 15,
                'account_balance' => 40,
            ],
            [
                'name' => 'Southampton',
                'league_id' => 1,
                'city' => 11,
                'country' => 1,
                'coefficient' => 8,
                'coeff1' => 0,
                'coeff2' => 0,
                'coeff3' => 0,
                'coeff4' => 2,
                'coeff5' => 6,
                'world_ranking' => 5000,
                'stadium_id' => 16,
                'account_balance' => 32,
            ],
            [
                'name' => 'Tottenham Hotspur',
                'league_id' => 1,
                'city' => 1,
                'country' => 1,
                'coefficient' => 67,
                'coeff1' => 15,
                'coeff2' => 9,
                'coeff3' => 12,
                'coeff4' => 10,
                'coeff5' => 21,
                'world_ranking' => 8000,
                'stadium_id' => 17,
                'account_balance' => 60,
            ],
            [
                'name' => 'Watford',
                'league_id' => 1,
                'city' => 12,
                'country' => 1,
                'coefficient' => 0,
                'coeff1' => 0,
                'coeff2' => 0,
                'coeff3' => 0,
                'coeff4' => 0,
                'coeff5' => 0,
                'world_ranking' => 3900,
                'stadium_id' => 18,
                'account_balance' => 15,
            ],
            [
                'name' => 'West Ham United',
                'league_id' => 1,
                'city' => 1,
                'country' => 1,
                'coefficient' => 3,
                'coeff1' => 0,
                'coeff2' => 0,
                'coeff3' => 1,
                'coeff4' => 2,
                'coeff5' => 0,
                'world_ranking' => 4900,
                'stadium_id' => 19,
                'account_balance' => 35,
            ],
            [
                'name' => 'Wolverhampton Wanderers',
                'league_id' => 1,
                'city' => 13,
                'country' => 1,
                'coefficient' => 0,
                'coeff1' => 0,
                'coeff2' => 0,
                'coeff3' => 0,
                'coeff4' => 0,
                'coeff5' => 0,
                'world_ranking' => 3700,
                'stadium_id' => 20,
                'account_balance' => 20,
            ],
        ];
    }
}