name: Tests

on:
  push:
    branches:
      - main

jobs:
  build-front:
    name: Compile CSS and JS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Compile CSS and JS
        run: |
          npm install
          npm run production

  build-php:
    name: Install packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          extensions: mbstring, ctype, fileinfo, openssl, PDO, bcmath, json, tokenizer, xml
      - name: Run composer
        run:
          composer install --no-dev --no-interaction --prefer-dist
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          extensions: mbstring, ctype, fileinfo, openssl, PDO, bcmath, json, tokenizer, xml
      - name: Run composer
        run:
          composer install --no-interaction
      - name: Copy env file
        run:
          cp .env.example .env
      - name: Run test suite
        run:
          vendor/bin/phpunit
